apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kutt
  namespace: default
spec:
  values:
    ingress:
      hosts:
        - host: s-r.io
          paths:
            - path: /
              pathType: Prefix
        - host: seru.us
          paths:
            - path: /
              pathType: Prefix
    kutt:
      google:
        existingSecret: kutt-secrets
      recaptcha:
        existingSecret: kutt-secrets
      jwt:
        existingSecret: kutt-secrets
      mail:
        from: "${NOREPLY_SEND_EMAIL}"
        username: "${NOREPLY_AUTH_EMAIL}"
        password: "${NOREPLY_PASSWORD}"
        reportEmail: "${ADMIN_EMAIL}"
    postgresql:
      enabled: false
    externalPostgresql:
      # During migration: use existing Bitnami secret
      # After migration: change to kutt-postgresql-cnpg-cluster-app with key 'password'
      auth:
        existingSecret: kutt-secrets
        userPasswordKey: postgres-password
    redis:
      enabled: false
    externalRedis:
      auth:
        enabled: true
        existingSecret: kutt-secrets
        userPasswordKey: redis-password
