apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kutt
  namespace: default
spec:
  valuesFrom:
    - kind: Secret
      name: noreply-email-secrets
      valuesKey: NOREPLY_SEND_EMAIL
      targetPath: kutt.mail.from
      optional: false
    - kind: Secret
      name: noreply-email-secrets
      valuesKey: NOREPLY_AUTH_EMAIL
      targetPath: kutt.mail.username
      optional: false
    - kind: Secret
      name: noreply-email-secrets
      valuesKey: NOREPLY_PASSWORD
      targetPath: kutt.mail.password
      optional: false
  values:
    ingress:
      hosts:
        - host: s-r.io
          paths:
            - path: /
              pathType: Prefix
        - host: seru.us
          paths:
            - path: /
              pathType: Prefix
    kutt:
      google:
        existingSecret: kutt-secrets
      recaptcha:
        existingSecret: kutt-secrets
      jwt:
        existingSecret: kutt-secrets
      mail:
        reportEmail: "${ADMIN_EMAIL}"
    postgresql:
      enabled: false
    externalPostgresql:
      # Using password from kutt-secrets (set via CNPG cluster bootstrap)
      auth:
        existingSecret: kutt-secrets
        userPasswordKey: password
    redis:
      enabled: false
    externalRedis:
      auth:
        enabled: true
        existingSecret: kutt-secrets
        userPasswordKey: redis-password
