# MIGRATION: Remove this file after migration to CloudNativePG is complete
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kutt-postgresql
  namespace: default
spec:
  values:
    image:
      tag: 17.6.0-debian-12-r4
    metrics:
      image:
        tag: 0.17.1-debian-12-r16
    auth:
      existingSecret: kutt-secrets
      secretKeys:
        adminPasswordKey: "postgres-root-password"
        userPasswordKey: "postgres-password"

