apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kutt-redis
  namespace: default
spec:
  values:
    image:
      tag: 8.4.0
    auth:
      existingSecret: kutt-secrets
      existingSecretPasswordKey: redis-password
