apiVersion: networking.k8s.io/v1
kind: HelmRelease
metadata:
  name: vaultwarden-hr
  namespace: default
spec:
  valuesFrom:
    - kind: Secret
      name: noreply-email-secrets
      valuesKey: NOREPLY_SEND_EMAIL
      targetPath: smtp.from
      optional: false
    - kind: Secret
      name: noreply-email-secrets
      valuesKey: NOREPLY_AUTH_EMAIL
      targetPath: smtp.username.value
      optional: false
    - kind: Secret
      name: noreply-email-secrets
      valuesKey: NOREPLY_PASSWORD
      targetPath: smtp.password.value
      optional: false
  values:
    resourceType: Deployment
    domain: https://vault.${SECRET_DOMAIN}
    ingress:
      enabled: true
      hostname: vault.${SECRET_DOMAIN}
      additionalHostnames:
        - bitwarden.${SECRET_DOMAIN}
    adminToken:
      existingSecret: vaultwarden-secrets
      existingSecretKey: adminToken
    yubico:
      clientId: ${YUBICO_CLIENT_ID}
      secretKey: ${YUBICO_SECRET_KEY}
    smtp:
      fromName: "Bitwarden @ Serubin.net"
