apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: lacework-agent
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: lacework-agent
      version: v0.22.3
      sourceRef:
        kind: HelmRepository
        name: lacework-charts
        namespace: default
  values:
    laceworkConfig:
      accessToken: ""
