apiVersion: batch/v1
kind: CronJob
metadata:
  name: restic-check
  namespace: default  # Change me
spec:
  concurrencyPolicy: Forbid
  schedule: "20 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: restic
            image: restic/restic:latest
            workingDir: /data
            args:
              - check
              - --host
              - ${CLUSTER_HOST}  # set a consistent hostname to avoid restic rescans
              - .           # use workingDir to set path
            env:
              - name: RESTIC_REPOSITORY
                valueFrom:
                  secretKeyRef:
                    name: restic-secrets
                    key: RESTIC_REPOSITORY
                    optional: false
              - name: RESTIC_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: restic-secrets
                    key: RESTIC_PASSWORD
                    optional: false
              - name: B2_ACCOUNT_ID
                valueFrom:
                  secretKeyRef:
                    name: restic-secrets
                    key: B2_ACCOUNT_ID
                    optional: false
              - name: B2_ACCOUNT_KEY
                valueFrom:
                  secretKeyRef:
                    name: restic-secrets
                    key: B2_ACCOUNT_KEY
                    optional: false
