apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-cnpg-backup-crypto-secret
  annotations:
    policies.kyverno.io/title: Restrict CNPG Backup Crypto Secret Access
    policies.kyverno.io/description: >-
      Only Longhorn CSI and specific backup-related workloads can use the
      cnpg-backup-crypto secret. This prevents other pods from accessing
      the volume encryption key.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: restrict-secret-mount
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - default
      preconditions:
        all:
          # Only apply to pods that try to mount the crypto secret
          - key: "cnpg-backup-crypto"
            operator: AnyIn
            value: "{{ request.object.spec.volumes[?secret].secret.secretName }}"
      validate:
        message: "Only Longhorn CSI can access the cnpg-backup-crypto secret"
        deny:
          conditions:
            all:
              # Deny if not a Longhorn CSI pod
              - key: "{{ request.object.metadata.labels.\"app\" || '' }}"
                operator: NotEquals
                value: "csi-attacher"
              - key: "{{ request.object.metadata.labels.\"app\" || '' }}"
                operator: NotEquals
                value: "csi-provisioner"
              - key: "{{ request.object.metadata.labels.\"app\" || '' }}"
                operator: NotEquals
                value: "longhorn-csi-plugin"
