apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cnpg-backups-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 15Gi
