apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: vaultwarden
      version: v0.22.3
      sourceRef:
        kind: HelmRepository
        name: vaultwarden-charts
        namespace: default
  values:
    image:
      registry: docker.io
      repository: vaultwarden/server
      tag: "1.32.6-alpine"
    signupsAllowed: false
    ingress:
      enabled: true
      class: ""
    data:
      name: "vaultwarden-data"
      size: "10Gi"
      class: "local-path"
      keepPvc: true
    smtp:
      enabled: true
      host: "smtp.gmail.com"
      port: 465
      security: "force_tls"
