apiVersion: v1
kind: Service
metadata:
  name: dysautonomia-web-service
  namespace: default

spec:
  ports:
    - name: web
      port: 80
      targetPort: web

  selector:
    app: dysautonomia-web
