apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-outpost-ops
  namespace: default
  labels:
    app.kubernetes.io/instance: authentik
    app.kubernetes.io/name: authentik
spec:
  routes:
    - match: (Host(`ops.${SECRET_DOMAIN}`) || Host(`prometheus.${SECRET_DOMAIN}`) || Host(`alert-manager.${SECRET_DOMAIN}`)) && PathPrefix(`/outpost.goauthentik.io`)
      kind: Rule
      services:
        - name: authentik-server
          port: 80
