apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik-postgresql-cnpg
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: cluster
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: cloudnativepg-charts
        namespace: default
      interval: 5m
  values:
    name: authentik-postgresql-cnpg
    cluster:
      instances: 1
      storage:
        size: 4Gi
        storageClass: longhorn
      monitoring:
        enabled: true
        podMonitor:
          enabled: true
      initdb:
        database: authentik
        owner: authentik
        # Secret must have 'username' and 'password' keys

