apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana
  - ops
  - prometheus
  - alertmanager
  - synology
  - media
  - jellyfin
  - embedded-outpost
  - home-outpost
  - groups
