apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/changedetection
  - changedetection.ingressroute.yaml
patches:
  - path: changedetection.hr.yaml
    target:
      kind: HelmRelease
      name: changedetection
