apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-encrypted
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  encrypted: "true"
  # Per-PVC secret via annotations (escaped for Flux envsubst)
  csi.storage.k8s.io/provisioner-secret-name: $${pvc.annotations['longhorn.io/crypto-key-secret-name']}
  csi.storage.k8s.io/provisioner-secret-namespace: $${pvc.annotations['longhorn.io/crypto-key-secret-namespace']}
  csi.storage.k8s.io/node-publish-secret-name: $${pvc.annotations['longhorn.io/crypto-key-secret-name']}
  csi.storage.k8s.io/node-publish-secret-namespace: $${pvc.annotations['longhorn.io/crypto-key-secret-namespace']}
  csi.storage.k8s.io/node-stage-secret-name: $${pvc.annotations['longhorn.io/crypto-key-secret-name']}
  csi.storage.k8s.io/node-stage-secret-namespace: $${pvc.annotations['longhorn.io/crypto-key-secret-namespace']}
