kind: Deployment
apiVersion: apps/v1
metadata:
  name: aj4democracy
  namespace: default
  labels:
    app: aj4democracy

spec:
  replicas: 1
  selector:
    matchLabels:
      app: aj4democracy
  template:
    metadata:
      labels:
        app: aj4democracy
    spec:
      containers:
        - name: aj4democracy
          image: ghcr.io/serubin/ajd-site:2026.1.10
          ports:
            - name: web
              containerPort: 80
