apiVersion: v1
kind: ConfigMap
metadata:
  name: media-users-group-blueprint
  namespace: default
data:
  media-users-group.yaml: |
    version: 1
    metadata:
      name: media-users-access-group
    entries:
      - model: authentik_core.group
        id: media-users-group
        state: created
        identifiers:
          name: Media Users
        attrs:
          is_superuser: false
      - model: authentik_policies.policybinding
        identifiers:
          target: !Find [authentik_core.application, [slug, media-stack]]
          group: !KeyOf media-users-group
          order: 0
        attrs:
          enabled: true
