apiVersion: v1
kind: ConfigMap
metadata:
  name: ops-group-blueprint
  namespace: default
data:
  ops-group.yaml: |
    version: 1
    metadata:
      name: ops-access-group
    entries:
      - model: authentik_core.group
        id: ops-group
        state: created
        identifiers:
          name: Ops
        attrs:
          is_superuser: false
      - model: authentik_policies.policybinding
        identifiers:
          target: !Find [authentik_core.application, [slug, grafana]]
          group: !KeyOf ops-group
          order: 0
        attrs:
          enabled: true
      - model: authentik_policies.policybinding
        identifiers:
          target: !Find [authentik_core.application, [slug, ops]]
          group: !KeyOf ops-group
          order: 0
        attrs:
          enabled: true
      - model: authentik_policies.policybinding
        identifiers:
          target: !Find [authentik_core.application, [slug, longhorn]]
          group: !KeyOf ops-group
          order: 0
        attrs:
          enabled: true
      - model: authentik_policies.policybinding
        identifiers:
          target: !Find [authentik_core.application, [slug, weave-gitops]]
          group: !KeyOf ops-group
          order: 0
        attrs:
          enabled: true
      - model: authentik_policies.policybinding
        identifiers:
          target: !Find [authentik_core.application, [slug, traefik-dashboard]]
          group: !KeyOf ops-group
          order: 0
        attrs:
          enabled: true
      - model: authentik_policies.policybinding
        identifiers:
          target: !Find [authentik_core.application, [slug, prometheus]]
          group: !KeyOf ops-group
          order: 0
        attrs:
          enabled: true
      - model: authentik_policies.policybinding
        identifiers:
          target: !Find [authentik_core.application, [slug, alertmanager]]
          group: !KeyOf ops-group
          order: 0
        attrs:
          enabled: true
