apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 5m
  chart:
    spec:
      chart: kyverno
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: kyverno-charts
        namespace: default
      interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    replicaCount: 1
    metrics:
      serviceMonitor:
        enabled: false
    initContainer:
      image:
        tag: v1.16.0
