apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jpat-web-ingress
  namespace: default
spec:
  rules:
    - host: jessepaterson.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jpat-web
                port:
                  name: web
