apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: polr
  namespace: default
spec:
  values:
    ingress:
      hosts:
        - host: short.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
    postgresql:
      auth:
        existingSecret: kutt-secrets
    redis:
      auth:
        password: "${KUTT_REDIS_PASSWORD}"
