apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kutt
  namespace: default
spec:
  values:
    ingress:
      hosts:
        - host: short.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
    kutt:
      google:
        existingSecret: kutt-secrets
      recaptcha:
        existingSecret: kutt-secrets
      jwt:
        existingSecret: kutt-secrets
      mail:
        from: "${NOREPLY_SEND_EMAIL}"
        username: "${NOREPLY_AUTH_EMAIL}"
        password: "${NOREPLY_PASSWORD}"
        reportEmail: "${ADMIN_EMAIL}"
    postgresql:
      auth:
        existingSecret: kutt-secrets
    redis:
      auth:
        password: "${KUTT_REDIS_PASSWORD}"
