apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: default
spec:
  valuesFrom:
    - kind: Secret
      name: authentik-secrets
      valuesKey: secret_key
      targetPath: authentik.secret_key
      optional: false
    - kind: Secret
      name: authentik-secrets
      valuesKey: password
      targetPath: authentik.postgresql.password
      optional: false
    - kind: Secret
      name: noreply-email-secrets
      valuesKey: NOREPLY_SEND_EMAIL
      targetPath: authentik.email.from
      optional: false
    - kind: Secret
      name: noreply-email-secrets
      valuesKey: NOREPLY_AUTH_EMAIL
      targetPath: authentik.email.username
      optional: false
    - kind: Secret
      name: noreply-email-secrets
      valuesKey: NOREPLY_PASSWORD
      targetPath: authentik.email.password
      optional: false
  values:
    authentik:
      email:
        host: smtp.gmail.com
        port: 587
        use_tls: true
      env:
      - name: GRAFANA_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: grafana-auth-secrets
            key: grafana-client-secret
    blueprints:
      configMaps:
        - grafana-blueprint
    server:
      ingress:
        hosts:
          - auth2.${SECRET_DOMAIN}
