apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: default
spec:
  values:
    authentik:
      # Cluster must provide
      # secret_key: via secret
      postgresql:
        # Cluster must provide
        # password: via secret
      email:
        host: smtp.gmail.com
        port: 587
        use_tls: true
        from: "${NOREPLY_SEND_EMAIL}"
        username: "${NOREPLY_AUTH_EMAIL}"
        password: "${NOREPLY_PASSWORD}"
    server:
      ingress:
        hosts:
          - auth2.${SECRET_DOMAIN}

