apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami-charts
  namespace: default
spec:
  type: oci
  interval: 30m
  url: oci://registry-1.docker.io/bitnamicharts
  timeout: 2m
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bjw-s-charts
  namespace: default
spec:
  type: oci
  interval: 30m
  url: oci://ghcr.io/bjw-s/helm
  timeout: 2m
