apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tandoor-postgresql
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 14.2.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
      interval: 5m
  values:
    auth:
      username: tandoor-receipes
      database: tandoor-receipes
    primary:
      persistence:
        enabled: true
        existingClaim: tandoor-postgresql-pvc
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
