apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tandoor-receipes
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: default
  dependsOn:
    - name: tandoor-postgresql
      namespace: default
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/tandoorrecipes/recipes
              tag: 1.5.13
            env:
              SECRET_KEY: ${TANDOOR_DB_PASSWORD}
              TIMEZONE: America/New_York
              DB_ENGINE: django.db.backends.postgresql
              POSTGRES_HOST: tandoor-postgresql
              POSTGRES_PORT: "5432"
              POSTGRES_DB: tandoor-receipes
              POSTGRES_USER: tandoor-receipes
              POSTGRES_PASSWORD: ${TANDOOR_DB_PASSWORD}
              # Serve mediafiles directly using gunicorn. Basically everyone recommends not doing this. Please use any of the examples
              # provided that include an additional nxginx container to handle media file serving.
              # If you know what you are doing turn this back on (1) to serve media files using djangos serve() method.
              # when unset: 1 (true) - this is temporary until an appropriate amount of time has passed for everyone to migrate
              GUNICORN_MEDIA: 1
              ENABLE_SIGNUP: 0
              ENABLE_METRICS: 1
              ENABLE_PDF_EXPORT: 1
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        hosts:
          - host: recipes.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
    persistence:
      static:
        existingClaim: tandoor-static-pvc
        globalMounts:
          - path: /opt/recipes/staticfiles
      media:
        existingClaim: tandoor-media-pvc
        globalMounts:
          - path: /opt/recipes/mediafiles
