apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kutt
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: kutt
      version: 7.0.0
      sourceRef:
        kind: HelmRepository
        name: christianhuth-helm-chart
        namespace: default
  values:
    image:
      repository: kutt/kutt
      tag: "v3.2.3"
    labels:
      app: kutt
    ingress:
      enabled: true
    kutt:
      admin:
        emails: "${EMAIL}"
      config:
        disallowAnonymousLinks: true
        disallowRegistration: true
      domain:
        useFirstIngressHost: true
      mail:
        host: smtp.gmail.com
        secure: true
    postgresql:
      enabled: false
    externalPostgresql:
      # Using CloudNativePG cluster
      hostname: kutt-postgresql-cnpg-cluster-rw
      port: 5432
      auth:
        database: kutt
        username: kutt
    redis:
      enabled: false
    externalRedis:
      # Cluster must provide
      # auth:
      #   existingSecret (secret key is password)
      #
      hostname: kutt-redis-master
      port: 6379
      auth:
        enabled: true
