apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kutt-postgresql-cnpg
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: cluster
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: cloudnativepg-charts
        namespace: default
      interval: 5m
  values:
    name: kutt-postgresql-cnpg
    cluster:
      instances: 1
      storage:
        size: 4Gi
        storageClass: local-path
      monitoring:
        enabled: true
        podMonitor:
          enabled: true
      bootstrap:
        initdb:
          database: kutt
          owner: kutt

