# MIGRATION: Remove this file after migration to CloudNativePG is complete
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kutt-postgresql
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 16.7.27
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: default
      interval: 5m
  values:
    image:
      repository: bitnamilegacy/postgresql
    auth:
      username: kutt
      database: kutt
    primary:
      persistence:
        enabled: true
        existingClaim: kutt-postgresql-pvc
    metrics:
      enabled: true
      image:
        repository: bitnamilegacy/postgres-exporter
      serviceMonitor:
        enabled: true

