apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kutt-redis
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: 0.17.5
      sourceRef:
        kind: HelmRepository
        name: cloudpirates-charts
        namespace: default
      interval: 5m
  values:
    fullnameOverride: kutt-redis
    architecture: standalone
    persistence:
      enabled: true
      existingClaim: kutt-redis-pvc
    auth:
      enabled: true
