apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kutt-redis
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: 22.0.7
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: default
      interval: 5m
  values:
    architecture: standalone
    image:
      repository: bitnamilegacy/redis
    master:
      persistence:
        enabled: true
        existingClaim: kutt-redis-pvc
    metrics:
      enabled: true
      image:
        repository: bitnamilegacy/redis-exporter
      serviceMonitor:
        enabled: true
    auth:
      enabled: true

