apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: velero-charts
  namespace: default
spec:
  interval: 30m
  timeout: 2m
  url: https://vmware-tanzu.github.io/helm-charts
