apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authelia-postgresql
  namespace: default
spec:
  values:
    image:
      repository: postgres
      tag: 18.1-alpine
    auth:
      username: authelia
      database: authelia
      existingSecret: authelia-secrets
      secretKeys:
        adminPasswordKey: "POSTGRES_ROOT_PASSWORD"
        userPasswordKey: "POSTGRES_PASSWORD"
