apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia-postgresql-cnpg
  namespace: default
spec:
  values:
    cluster:
      postgresql:
        parameters:
          max_connections: "100"
