apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia-redis
  namespace: default
spec:
  values:
    image:
      tag: 8.4.0
    auth:
      existingSecret: authelia-secrets
      existingSecretPasswordKey: REDIS_PASSWORD
