apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authelia-redis
  namespace: default
spec:
  values:
    image:
      repository: bitnamilegacy/redis
      tag: 8.2.1-debian-12-r0
    auth:
      existingSecret: authelia-secrets
      existingSecretPasswordKey: REDIS_PASSWORD
