apiVersion: v1
kind: Secret
metadata:
    name: authelia-users
    namespace: default
stringData:
    users_database.yml: ENC[AES256_GCM,data:r5e12V4zQiEHKKAmrKhsE6E1D/Z24JnQyhaR6jnfxxIvpWZKbxevAXyw3IRZowyeaR8XKod/OW8dV1c8RPEOvlx4ZqAT/yWRZerkiDHSKiuqCZHKdWApBAuueEkY3KMoHR6pgf87BCRMRnP3pvApUm9SV/Wo3q5N0H2JAZTA7P2o+7ITADR4kiM1k8FKCCngbYC76J/tO6moAvX2NBpigRDt9P9W3SLx0KqTP1vjZ2Aq1fBANOtHfpPrz6+ExUNB/3p5SMLACRjAxn6EIcVrV6eJFacYjF+US/YhgDxf6AgZ5TJPwsrqg2XOpRgsDC6MiHs72yw2j7CMAgGqF7s6DiLL80MR2vfC2ANYwSbS4UuBDdpQ,iv:/0PfUYf0yq607kVySfvid+2p5flpn7HkExbNcwFMQMs=,tag:pUqYXZYW8rnES+bMtrVHSQ==,type:str]
sops:
    lastmodified: "2025-12-10T00:36:59Z"
    mac: ENC[AES256_GCM,data:2p1V9qoeJsZBzzwMyjPrZVgtHMS5mwLW3UzqgoVAmH0CGIyMBfw1u1V6ucFuBHXavdRgNHDYQwjtjE9SR1qVowGTUN6tBQ52xvT1JIvcAjWrUV/XAicX0/qIeNCQs+BFymeqoYo0LboklBicWWTB1G/5Yo3i8XmP2UnYlkddhIU=,iv:ra68zqW4SkqJBvqMnK5px+BvCFK7EqQpg1/GZDbHuTw=,tag:wjUjjA2ducjFBdo50CxjFA==,type:str]
    pgp:
        - created_at: "2025-12-10T00:36:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0i7SvTnDueaAQ//QBDpqjWgoUIkASjsk3jffFWx6p/DlmeSgs+5I9mua7MH
            Vm1WT1YKxQNGqoqhvhYRwzpUVQ5AWvyoaCzOdOW6bbMVtcq2wcRf/Yf3m+pQRY88
            2WYRDHvMFImiBoe1AOygc3q/Hs7x48vgpsevO+cMqozVIEfF3MyTmKbvVcABoizr
            sm1EQ5l0s0Gxhdqbis+wxexZP9PlwOWoz098x1ngqrBf3qKv0b9VtehZ5paKVr0V
            F5M+OcINxNb9ggoxls42WJPhbJfeOEP526fKSxW1rVRotZbbt43KE0badXyvc0IS
            wr5Gua07LnYtamVnqXrubduF3wYB5ktfwfwCPv7+JtK0eSev8tmIGFMJ8qvzrlJP
            Qp7PfPhQ12Ln9o1eMlOVWOkMqe5tA9uIVuGTy+mgxaT4Eke+JG89dwkxE/F1L+Pt
            +l1OBW+ITbkB8HfjAXyLu6T3IDY/2uFJUfp0rjy/3MHbgGpVAYQjcHEjhp4xcixG
            Ea4tvqU+da/u93tuGz8KxALTyYQvmm2rK6ZN8oT3S3xSoB6eMIcDW6OByD3ie7OO
            ktU/HOp51SOmk4NhUosy2loajQbjc/QuzGQefB6gTVYlWEJGuOt6IRO0OyLJxzOR
            2NAUq8FgXghHNLCVjqPMueaTFhAMAOabEQpQX6CPYolvDIjx3qN4DAHNP1znHrDS
            XgHGAMpRRObx0dX1i2LDO54HpFt4SmvSv7Fa2M6EJK5Dn7btYY4bR+SJ40OfrJnr
            miVSi7TBu8x70evHiWOBz8iT9FHk+jvVfrzXpa0vEV8od67CpnXHwG/NjG/9PZ8=
            =eBdV
            -----END PGP MESSAGE-----
          fp: 7EB1A78D86B11352982D3A1F7037153C2DB9CDBD
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
