apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nocodb-minio-pvc
  namespace: default
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
