apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nocodb-minio
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      version: 5.4.0
      sourceRef:
        kind: HelmRepository
        name: minio-charts
        namespace: default
      interval: 5m
  values:
    fullnameOverride: nocodb-minio
    mode: standalone
    replicas: 1
    persistence:
      enabled: true
      existingClaim: nocodb-minio-pvc
      size: 10Gi
    buckets:
      - name: nocodb
        policy: none
        purge: false
    service:
      type: ClusterIP
      port: "9000"
    consoleService:
      type: ClusterIP
      port: "9001"
    resources:
      requests:
        memory: 512Mi
