apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../base/lemonhope
  - lemonhope.sops.yaml
patches:
  - path: lemonhope.yaml
    target:
      kind: Deployment
