apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-data
  namespace: flux-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M
  storageClassName: local-path
