apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: tandoor-postgresql
  namespace: default
spec:
  values:
    auth:
      username: tandoor-receipes
      database: tandoor-receipes
      existingSecret: tandoor-secrets
      secretKeys:
        adminPasswordKey: "POSTGRES_ROOT_PASSWORD"
        userPasswordKey: "POSTGRES_PASSWORD"
