apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tandoor-postgresql
  namespace: default
spec:
  values:
    image:
      tag: 17.6.0-debian-12-r4
    metrics:
      image:
        tag: 0.17.1-debian-12-r16
    auth:
      username: tandoor-receipes
      database: tandoor-receipes
      existingSecret: tandoor-secrets
      secretKeys:
        adminPasswordKey: "POSTGRES_ROOT_PASSWORD"
        userPasswordKey: "POSTGRES_PASSWORD"
