apiVersion: v1
kind: Secret
metadata:
    name: tandoor-secrets
    namespace: default
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:bRzMFIr5nBsjUB8fQnlk+hx6w+/WUBkYqLuoQfBfafgmco31MENDTiJ12ZR4Pm5H5Ba4sy4syfZTtaMqsYtOSg==,iv:TKuKW6rRbkAV4CCyf81kmgMlG2QXDX7lV0MITWf9TQI=,tag:S1NgOKJ7Fuplw76RdrdwCg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:fUVI/NShJ7T1jtGld4l9ouXKx+r6SrytIAox3JLBxaj+ifqlmRSTvS8wQBqDJd3fxNQmHWheo2PnGPXt2du6Fg==,iv:dLZWlSggSeLDbtZr9fi1YQZ6A09xYh15nErWlAP7Q6M=,tag:3Rdpt1+rpMecKzQfD5UyQQ==,type:str]
    POSTGRES_ROOT_PASSWORD: ENC[AES256_GCM,data:Nu7VAS3QayEAiHyIzszOP6x+Kig/mtxME7sEfRUgSlwXwf+nFnWHwvOSMon+XqhSbE2UJIO12lhgd8AkxGpO5w==,iv:1TmlPXFexWNGFFlfKBYqlEcbciGuZ3Es571Bf8uyn78=,tag:5Vkp5fDPiILWTBe01u9glg==,type:str]
sops:
    lastmodified: "2025-12-10T00:36:58Z"
    mac: ENC[AES256_GCM,data:edXSBJ9rE1qod05xg1yvEzeCmSgWCs8kDezug833cB+hjoKIOzEa3iUeUxcXuPvmIDpLsNMaZB+ttZPrAhGJXYPUqrFUSswSrHefjwdkv2PRv2U+w57h+j1Hdv/LEVlmME1jd+WVNhV+oPUeRcz8vvLx+cqF/gfHFNTDTiv7Rcc=,iv:oXg/QyIM2hYGjQvusMfPk+qXg4vgkCjSouXKBZp3Xzc=,tag:hYgzMHGHvSgyIQDYv2aY6Q==,type:str]
    pgp:
        - created_at: "2025-12-10T00:36:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0i7SvTnDueaAQ/9E/V7WgHEsCHhCiaaXoYuNiBJk6lKAqaCOak/ZmEcOXMS
            IHtlAFBsqj0YGjtuwkE3Jfa+HjnElseXzkVoi5nuAPUOs96VA/ktF7fz/DXrOnTO
            pPqvMsxCLwuVidIBM6viv1w/SzExv4vB8nIxOvPbQ4QyOwJ+iCcSwSgol7+1wuR5
            x+6yk//n8ivxlqCC2//h2FMMk52/THfo0TiFMUoG/Cj9XKitWF/lsUHFV8aRpAnT
            Gt2neMAKfNWmFXHIUD00vbmTmiRTTDj8mkCE5EIuwY3EbvZ7H/2TVubGUgsOpVZX
            HqiWaFow7fTVOtZn/eNm1YTEb1R6tElWlPzjrzwNaycKEG3AdTCRSI4rSdI52j9b
            V3w8VYzWD/7W6BTxdwdWdBox3GbWal2p3fA2Q2/PSC+xaPkTu+1NkCVuHCLMWfbx
            Hly1tZ0XukSBcqO9343OpUcfBNAac1nmoLnORZ7Gl+zHf4DeA5iqPnqLA05z8xdY
            q2/QATlrLwMOt5zEnOOuQl3U8NFlyWZjDCAX87q0QYRR0GvCqWwR+dVWEBX4mCm8
            7wXDOKV21iPmmtkB8ubZxXJDY+azqQkpkF0O1kHEN17GyVO7speczZw/HvX+oQEW
            zN2Sms7OfLvEY/u9lZ20vdt3uUJYehRnQH/udVsgJRGIjcLryW0vUhXAgJ0KyPTS
            XgEg+xs5fnZaOvfeuE1ycDcCjfQe/y2gVU5Y+TrSyuQb/6Ex2JUSxrd4rH/3xaEL
            qOqbhyC6IkIvmtPXpEbmGAE57a5xcJx6qMQ5c7nQeOfePVRN29TFPMj+Kl2qteA=
            =nL9h
            -----END PGP MESSAGE-----
          fp: 7EB1A78D86B11352982D3A1F7037153C2DB9CDBD
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
