apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-longhorn-backup-secret-access
  annotations:
    policies.kyverno.io/title: Restrict Longhorn Backup Secret Access
    policies.kyverno.io/description: >-
      Only Longhorn pods in the longhorn-system namespace can access the
      longhorn-backup-secret. This prevents unauthorized access to backup
      credentials.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: restrict-secret-volume-mount
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          # Only apply to pods that try to mount the backup secret as a volume
          - key: "longhorn-backup-secret"
            operator: AnyIn
            value: "{{ request.object.spec.volumes[?secret].secret.secretName }}"
      validate:
        message: "Only Longhorn pods in the longhorn-system namespace using the longhorn-service-account service account and longhornio/longhorn-manager image can mount the longhorn-backup-secret"
        cel:
          expressions:
            - expression: "object.metadata.namespace == 'longhorn-system'"
            - expression: "object.spec.serviceAccountName == 'longhorn-service-account'"
            - expression: "object.spec.containers.all(c, c.image.startsWith('longhornio/longhorn-manager:'))"
    - name: restrict-secret-env-reference
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          # Only apply to pods that try to use the backup secret in env vars
          - key: "longhorn-backup-secret"
            operator: AnyIn
            value: "{{ request.object.spec.containers[?env[?valueFrom.secretKeyRef]].env[?valueFrom.secretKeyRef].name }}"
      validate:
        message: "Only Longhorn pods in the longhorn-system namespace using the longhorn-service-account service account and longhornio/longhorn-manager image can use the longhorn-backup-secret in environment variables"
        cel:
          expressions:
            - expression: "object.metadata.namespace == 'longhorn-system'"
            - expression: "object.spec.serviceAccountName == 'longhorn-service-account'"
            - expression: "object.spec.containers.all(c, c.image.startsWith('longhornio/longhorn-manager:'))"
