apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plausible-clickhouse
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: default
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: clickhouse/clickhouse-server
              tag: "25.12-alpine"
            env:
              CLICKHOUSE_DB: plausible
              CLICKHOUSE_USER: plausible
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 8123
                  initialDelaySeconds: 30
                  periodSeconds: 10
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 8123
                  initialDelaySeconds: 10
                  periodSeconds: 5
    service:
      main:
        ports:
          http:
            port: 8123
          native:
            port: 9000
    persistence:
      data:
        existingClaim: plausible-clickhouse-pvc
        globalMounts:
          - path: /var/lib/clickhouse
      logs:
        type: emptyDir
        globalMounts:
          - path: /var/log/clickhouse-server
