apiVersion: v1
kind: Secret
metadata:
    name: media-auth-secrets
    namespace: default
type: Opaque
stringData:
    MEDIA_SHARED_PASSWORD: ENC[AES256_GCM,data:anSarkHAScuiJCkMX9iDrRgrD1VEGFEodTUIlqQlMp6CPL11BYGsXACyruxOLHW1Z+YVXWRnIO57OG90llUemA==,iv:SRniibojBu3GlySXLkEyb65m4DK3ixQ0kgEjEJezcok=,tag:aTaA6W5ZsJKby4WkBUCC5A==,type:str]
sops:
    lastmodified: "2026-05-09T15:00:31Z"
    mac: ENC[AES256_GCM,data:EHYchEFpVWFVsJ8DedPtxE967llsE3eIlhqkbwEl1Q1oKNdH8u14OXfcPtAzA0zE6PIx27n+vOYO4jhhl0II1onFkJxHXEd3QsUH/cU8ZOXw4WMUw+kMLNjZQTkCbsYaOnTYOW1z0n1UacATOkYsA4vGD6o0qdgcGYnUCbPNyuY=,iv:l1FfY1qJv2TES4sQ5xRm61hmIC/aKsHQHzfoX0hAcIo=,tag:IQXIGWnQL2VdT8aa10qYug==,type:str]
    pgp:
        - created_at: "2026-05-09T15:00:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0i7SvTnDueaAQ//bPGpZ/IKZIzZytKjXC4VHdjXbwxS0GEGh+5RImo8qBlF
            DAJyezfextbOu+UGAP7WYSbLHQQ3yoC2icMvaT+YZX9wDmu5tCbLlIMqI1sRFkPq
            p5S1q6sudGAIJDRz6JlVnKdkvDalb6tYaPa0dhfabmqBQQY5K32YAcG+hzLHmu2U
            Fy3zuxIIOUNDzrKy7vI6PMLp97cp3uYjR/dLGH0PVAj0LkoLEgDdkCTcX0I4fDvi
            9bsYMRB5d3UxVFtGg26RPT6GXfiH9RPrqrfogIO7S8UdIDpYE7isj3fW/8FE3NdI
            OfH4d2y86lzYFoZ44Cmp6+xrcqwO1Mn7083oPy3R5sOlixpB7wliX7Yzsn1VLtHO
            pDHKNfn1L28wiO0y3s7u/e2BonRXgozMH6pfYxIowaR52VkxsFZyqpXwxzxdHdmd
            EwukEymlh4UtRdQAppvghcHy3Y3JXEWwNtmubnGJY/QNAUjFSWdY1tpvNPBSCiYO
            v6ahF9yiazDh+djNOVEtsOEPU11R79Q3IRIK2JPZ+7o9YZnomyRD89u2gVum4xDI
            BQDGYWZv/5U9gbhsc/4hYUrz6Ydc++TmbVCYP/gQwEodvZnjiL0OaBQiGRuayqtb
            C+y+zAEaxwl/zHd0QhbZNFDtD1cm3Uz+Kt+OJ93mXWm+BiBrjW8wZq+32limPW7S
            XAEf0nEbPR8MLd9v/ZIu2swC8Vztg6kHLwaEQKvopViWtBopieGcEQzA5aQEM9Ux
            v/4vr9ytJYCZR72SYzcVqL6qsUmExbZNp+wZLW2EtLc488b9C3kqn50RAnIV
            =23J+
            -----END PGP MESSAGE-----
          fp: 7EB1A78D86B11352982D3A1F7037153C2DB9CDBD
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
