apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: lacework-agent
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: lacework-agent
      version: v6.13.0
      sourceRef:
        kind: HelmRepository
        name: lacework-charts
        namespace: default
  values:
    image:
      registry: docker.io
      repository: lacework/datacollector
      tag: 6.13.0
    datacollector:
      # Not required, but trying to be verbose
      enabled: true
    laceworkConfig:
      serverUrl: https://api.lacework.net
      # Cluster must provide this
      accessToken: ""
      containerEngineEndpoint: unix:///run/k3s/containerd/containerd.sock
      containerRuntime: containerd
      codeaware:
        enable: true
