apiVersion: networking.k8s.io/v1
kind: HelmRelease
metadata:
  name: polr-hr
  namespace: default
spec:
  values:
    ingress:
      hosts:
        - host: short.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix

    admin:
      username: ${ADMIN_USERNAME}
      existingSecret: polr-secrets
    mysql:
      enabled: true
      existingSecret: polr-secrets
    env:
      - name: APP_NAME
        value: "Polr"
      - name: APP_ADDRESS
        value: "short.${SECRET_DOMAIN}"
      - name: POLR_ALLOW_ACCT_CREATION
        value: "false"
      - name: POLR_ACCT_ACTIVATION
        value: "false"
      - name: SETTING_PUBLIC_INTERFACE
        value: "true"
      - name: SETTING_SHORTEN_PERMISSION
        value: "true"
