apiVersion: v1
kind: Secret
metadata:
    name: aj4democracy-secrets
    namespace: default
stringData:
    CMS_API_BASE_URL: ENC[AES256_GCM,data:wcRAJJIe7wqMnJl1aXXnD5SX,iv:PeMnwKiyasYQXfd0SZbMSlVRg5XGKQv7TCaSAc3YjtQ=,tag:SN12NLFrOXfaVy/G/ZdYHA==,type:str]
    CMS_API_TABLE_ID: ENC[AES256_GCM,data:XD8u6THBAda0Ox84xYOA,iv:AZgfiIkPx2wfx2WA0YbS65TrSBeLif8VRI5mOspzmKg=,tag:tURQ6gL0Inor4fxvRR3I8A==,type:str]
    CMS_API_VIEW_ID: ENC[AES256_GCM,data:7dcTK6cz6wZj0QN8fWIl4Q==,iv:VpzHMqa4fCKFQNT3ZXCuvBXBDANisFTsGPC3EDEK6m4=,tag:N3KWEK8KHCMNv7SdKm4SvA==,type:str]
    NOCODB_API_TOKEN: ENC[AES256_GCM,data:FAJcvgOjWWmAL9ZI6DLChKrQlUJze4fwaUPL+m6Yf1ooRrb4JY2EOA==,iv:l6/2LCV6kN2woJoOsR0mSW9lQCurqWugXVFsXRB1x+s=,tag:afiUfuFXiROQmmiI38Tr3w==,type:str]
sops:
    lastmodified: "2026-01-24T04:06:18Z"
    mac: ENC[AES256_GCM,data:q7JBULNh51bAItRkyxxwEd//cMx1K/kv6/vAoZ9PSttlFVYUU06btGrDc34wo6glZPVJIHTSkp4kMu6z9IMOivAc1S+TAA9d/GQMwmE0BtnRA6MbZFrMt8PVO0JFKWi3xXyzE/cllJ1290xvsvsrYBC6w6XydZL7F9DrUYqrGA8=,iv:5M3VLzMt9J/OyGdj/CO+F2il2V26Txlhn+nl1FoovWY=,tag:FdIMHlSTmL8lvrrPsKuBCg==,type:str]
    pgp:
        - created_at: "2026-01-24T03:55:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0i7SvTnDueaAQ//aNjGSLEDX1MOnx+XAYmhZuhPQFzyely2omdgxCkeW4lk
            FaR12PQntIYYC0PRu7RaF4Zlx9uPlS6uF41rfGpsHU6r4TvjwgNgsFHyx7S2mytL
            T/6b/iQdijZ+2ZMnmGISDXgRROKeaL0ftse9AWU+IRKHxW4h2CCg8ic+hCDuz0e7
            h+yH7HDc0SPIxvnEicwVoH7I75dlDmZqMtD6wN08ZEcIc75E/jvlyT1NP4TsTYGs
            GzhUzTXgtB4JQIiQVwS9Fw7pZ6PUuCYqhfzazE7y3ni88dEovvjYr5qVji4fpFPG
            OnzYNNGqJVbX+cEuP6nDd3+W1HXKOyh1VAyXcAM+B3zSeudJm4Pa6pyDhHYKB2Uy
            0SQa+mFXBQN6jrJuQo4z51qqKfEb93l/wnTvQTUOYwyI/+W3GVk7L7aGd5hhUJ+I
            BtYmaVh8mWBAObe/ZU9pyw9df1/v+xOaZEFj68RTh5G08ghaYhx07/YTOYxMYzYN
            SqtlginGlG6USEz4znU0iCa684mJueGW9hizhnA/6/JdreTh8eEEVQi8DgKsRXxc
            hOYrC1OI5mcnUIWpW5xXe86JP2nZmPBJD0xLODz2/GskY6D2/+jJGwGaQHK2/eIT
            KU/QhikZwsRl/tl3yHPmXq96Oficgzw6EXWf1jHUnCxWyo5LVEWEY1GTXPyJP+jS
            XgHp6NxJJ+WFRL+991WdnucfWgkTGG9aJ7NhqoWwzJnwh08gbYdvVe8pu2LNZL60
            25F/x3pF4IYkY77xiFFxSSOhGfb54skZTXsSLJ0zJlXBhuah6bOoiClwRCCvwJI=
            =udQB
            -----END PGP MESSAGE-----
          fp: 7EB1A78D86B11352982D3A1F7037153C2DB9CDBD
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
