kind: Deployment
apiVersion: apps/v1
metadata:
  name: aj4democracy
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: aj4democracy
          env:
            - name: nocodb__base_url
              valueFrom:
                secretKeyRef:
                  name: aj4democracy-secrets
                  key: nocodb__base_url
            - name: nocodb__api_token
              valueFrom:
                secretKeyRef:
                  name: aj4democracy-secrets
                  key: nocodb__api_token
            - name: nocodb__cms__table_id
              valueFrom:
                secretKeyRef:
                  name: aj4democracy-secrets
                  key: nocodb__cms__table_id
            - name: nocodb__cms__view_id
              valueFrom:
                secretKeyRef:
                  name: aj4democracy-secrets
                  key: nocodb__cms__view_id
            - name: nocodb__users__table_id
              valueFrom:
                secretKeyRef:
                  name: aj4democracy-secrets
                  key: nocodb__users__table_id
            - name: nocodb__users__view_id
              valueFrom:
                secretKeyRef:
                  name: aj4democracy-secrets
                  key: nocodb__users__view_id
            - name: nocodb__presigned_links__table_id
              valueFrom:
                secretKeyRef:
                  name: aj4democracy-secrets
                  key: nocodb__presigned_links__table_id
            - name: nocodb__presigned_links__view_id
              valueFrom:
                secretKeyRef:
                  name: aj4democracy-secrets
                  key: nocodb__presigned_links__view_id
            - name: nocodb__candidates__table_id
              valueFrom:
                secretKeyRef:
                  name: aj4democracy-secrets
                  key: nocodb__candidates__table_id
            - name: nocodb__candidates__view_id
              valueFrom:
                secretKeyRef:
                  name: aj4democracy-secrets
                  key: nocodb__candidates__view_id
            - name: features__geocodio_api_key
              valueFrom:
                secretKeyRef:
                  name: aj4democracy-secrets
                  key: features__geocodio_api_key
            - name: features__whatsapp_link
              valueFrom:
                secretKeyRef:
                  name: aj4democracy-secrets
                  key: features__whatsapp_link
            - name: features__email_enabled
              valueFrom:
                secretKeyRef:
                  name: aj4democracy-secrets
                  key: features__email_enabled
            - name: features__sms_enabled
              valueFrom:
                secretKeyRef:
                  name: aj4democracy-secrets
                  key: features__sms_enabled
            - name: twilio__account_sid
              valueFrom:
                secretKeyRef:
                  name: aj4democracy-secrets
                  key: twilio__account_sid
            - name: twilio__auth_token
              valueFrom:
                secretKeyRef:
                  name: aj4democracy-secrets
                  key: twilio__auth_token
            - name: twilio__from_email
              valueFrom:
                secretKeyRef:
                  name: aj4democracy-secrets
                  key: twilio__from_email
            - name: twilio__from_name
              valueFrom:
                secretKeyRef:
                  name: aj4democracy-secrets
                  key: twilio__from_name
            - name: twilio__messaging_phone_number
              valueFrom:
                secretKeyRef:
                  name: aj4democracy-secrets
                  key: twilio__messaging_phone_number
