apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: serubin-net-ingress
  namespace: default
spec:
  rules:
    - host: serubin.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: serubin-net
                port:
                  name: web
    - host: serubin.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: serubin-net
                port:
                  name: web
    - host: serub.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: serubin-net
                port:
                  name: web
    - host: solomonrubin.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: serubin-net
                port:
                  name: web
    - host: solomonrub.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: serubin-net
                port:
                  name: web
