apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: default
spec:
  values:
    additionalArgs:
      - --route-prefix=/weave
      - --insecure-no-authentication-user=admin # Must duplicate from Base
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: default-forwardauth-authentik@kubernetescrd
      hosts:
        - host: ops.${SECRET_DOMAIN}
          paths:
            - path: /weave
              pathType: Prefix
