apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: default
spec:
  values:
    ingress:
      hosts:
        - host: ${CLUSTER_HOST}
          paths:
            - path: /
              pathType: Prefix
