apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: default
spec:
  values:
    adminUser:
      # Todo, change this
      passwordHash: $2y$10$8D6ui.zsSPZgNQ8RKUUpsOKP8TOPl/xKZO2lnYAaia1rBsb2t9nXq
    ingress:
      hosts:
        - host: ${CLUSTER_HOST}
          paths:
            - path: /
              pathType: Prefix
