apiVersion: v1
kind: Secret
metadata:
    name: capacitor-next
    namespace: capacitor
type: Opaque
stringData:
    SESSION_HASH_KEY: ENC[AES256_GCM,data:IivJ8EjILp1T0yXL+J5rldq0Z6fWBXasV/tXp1ukUI+3eJ+kZc8nQXei82c=,iv:LEFtLUusbsgtpjqmKWjo09xtzii+c1Y09Jy55LoZYpM=,tag:RqcHvVyJ0fyWouJHPXrHeg==,type:str]
    SESSION_BLOCK_KEY: ENC[AES256_GCM,data:/hegHdPe8OvFNVKyXGYi+a4Lp84fdHCtuasls64e0lmgKRomlaOvnjqAfp8=,iv:gshndhqQkPZfkgqmxIpxmsPgukNvS3zkDU73nLt2naY=,tag:BlZSQq5NVOqcikthT8y4DQ==,type:str]
    registry.yaml: ENC[AES256_GCM,data:4GFgsOaiq370iMXrFn/DfbdNXC4tzXAUnetp/gUnDfRcMhRpL6Px8x8bF+xuH2NhTaKxmpt0c5FY7poVl3m3TTIpOh/djo+Nr8Nhe4Ex4fcB4JrZmEaLdEZbwdLeHsid/1Ozmjvpp/ELofAsIqIHdN8xvIzFyD0kO8M/BLTQJSG7hf+4JORSqVC8P8YrYD8rJ0THSM12eTaohoaBnlTm5Hx9egTnakDA57bWHy5CmBw20pRPqDlBJtJK7o1OFoW/HIcqmILPkxxvyGHRrbJYy2rKwOj9XFccCxPgL489WzGUdwY5nt0XHU9VIk29YOVeY4pGR12qwo+FZtecsarBeCWqZg==,iv:WbjNzSPGmOj6aPk7ewOBjpzIzRH/vzrS9xcWr1Ah6mQ=,tag:rABlqc0Q08oSVPdEwuIHSA==,type:str]
sops:
    lastmodified: "2026-05-10T22:49:54Z"
    mac: ENC[AES256_GCM,data:9adsgeYU1O94PPvtixrkL7YqRhxSnI1f2lnVqQcdeTas4a0W/2ST21jhzaU39MHYMcgaVgDfqj7aOWQKLVLmRmXR+pgDpjGCFj3xHqF1CjT4J35YuLd4T7U+k0gn9m2P+wxcxO2uf53MhZzj6DN1Tp5tOsNdNx/1/9mViRFs0Ts=,iv:ix/klsWg5B9E31U/21co4f1sSd1d+tcTkvPxOSCWohA=,tag:ocGGq6eoittwjfxYBIDclw==,type:str]
    pgp:
        - created_at: "2026-05-10T16:07:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0i7SvTnDueaAQ//eYeGTqPTpcr28dlurAESaJxHUg4WabrHUkZpVhJAbEd7
            gBZZ2B9pqFEWJj1GOXNVA6lWiSE3JbXhlBCkf+E0npS60J4z4icBqu2KHqJGZuSx
            t0g1mR4Y9l+s/cT6HyxnrTAAj6js8CwK8/6ztLhg++zluS9+lThQFRzO1M9bNj9p
            9dXS90RcAgNhyCmuM+KkMTimjMp+1fR0UCp8r2x7utRdWvqUsR8ln/sm2dZkdHVm
            /wXTXGnzxbzfrzbPt8y68cLKQLhIVp9+zhHlsVQq/b/AyQhn750JTwnjEC9rMa7k
            AVIp39gV4dldCErxLb1+ppMKyWwczvDHZ0EtRXWVgKLfmjBKtSNmKREkNGlZcg6S
            DMpBoVSv+opIZXkcHxoWTDWEToEfxWA8XT8FYSl8sXSkBoV9PJF9hTSveu+8PkKB
            dAMSGAmnyXzyQVzmm3lllaxKs+fJwEStR++5g/++QMsla/YD75+k+acMiPSrqHQP
            DQrEhmG9bW3kh9hp7W7kqu4ft30JRyFX9rUTb+48/NxcDXyUD8jYaIrxo1hI3RJ3
            xt5IimuU68dDmK/0C1/xyHz3BALBfoRL8+fOn6IgFebnsyFjmDR+gNy2Nmn4ZK0V
            1uLJGwnnEXBlC3YXB5beeiRldFiJKzoru5n+gSNW8iW5hA3OOT8rI3pTiqL6qHbS
            XAHK8aaQlc5XHnuWuc+6LP5hs+ZYupf4JbU5qzCZ01zi9F5BpqKQBcr6qfP8FSkE
            XI1yzqfEVwGtngWrVU4XyjekP4hSR+/gQgSNMJczQfOaAMZ1owNQKjKT5HZB
            =Iv99
            -----END PGP MESSAGE-----
          fp: 7EB1A78D86B11352982D3A1F7037153C2DB9CDBD
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
