# MIGRATION: Remove this file after migration to CloudNativePG is complete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-postgresql-pvc
  namespace: default
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

