apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia-postgresql-cnpg
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: cluster
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: cloudnativepg-charts
        namespace: default
      interval: 5m
  values:
    name: authelia-postgresql-cnpg
    cluster:
      instances: 1
      resources:
        requests:
          memory: 64Mi
        limits:
          memory: 256Mi
      storage:
        size: 4Gi
        storageClass: local-path
      monitoring:
        enabled: true
        podMonitor:
          enabled: true
      initdb:
        database: authelia
        owner: authelia
