---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authelia-postgresql
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 14.3.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: default
      interval: 5m
  values:
    auth:
      username: authelia
      database: authelia
    primary:
      persistence:
        enabled: true
        existingClaim: authelia-postgresql-pvc
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
