apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authelia-redis
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: 18.19.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: default
      interval: 5m
  values:
    architecture: standalone
    master:
      persistence:
        enabled: true
        existingClaim: authelia-redis-pvc
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    auth:
      existingSecret: authelia-secrets
      existingSecretPasswordKey: REDIS_PASSWORD
