apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-redis-pvc
  namespace: default
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
