apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia-redis
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: 0.17.5
      sourceRef:
        kind: HelmRepository
        name: cloudpirates-charts
        namespace: default
      interval: 5m
  values:
    fullnameOverride: authelia-redis
    architecture: standalone
    master:
      persistence:
        enabled: true
        existingClaim: authelia-redis-pvc
    auth:
      enabled: true
