apiVersion: v1
kind: Secret
metadata:
    name: velero-b2-credentials
    namespace: velero
type: Opaque
stringData:
    cloud: ENC[AES256_GCM,data:Gf1viqI3uWZSa0Gc6Mdfj7YMwaupHL5FB94GBIA6OzyZT487uu8GkvXKy8QtQ56vgflc0Nd+mT+M/sRmH/DHKCP9jfa12vacwPn5ynjeD86XyY1yPQP7zDkOhkl5ez0W6/G6gSqhP9IVuU1941yIdw==,iv:/g7vnm9bLwQecwAGRV88GNYF7Ffsd2J/pSUIDkbsZSU=,tag:FZIdkNB2n/PdL+oSLUvVig==,type:str]
sops:
    lastmodified: "2026-04-10T00:16:58Z"
    mac: ENC[AES256_GCM,data:0hi9ngugKGPekE98T8ozyBzNX7xV/gZxQJlH0Wppv82vXPpgzpALOtLX7alQR9uxpYcSf6E+d2cqVyjtwsshUtSm7guJLvsi2/4UyzUHRUc1vAyY1+zjhPjYUB0JZTLQC59qiw282z15S0LMrtJ060J7KlgathOIDruC/CMlUJ8=,iv:72J8eeWGvseZH0KhHhkbHTZM1PVqa0pCqagTXz//4QQ=,tag:qEmGiQHNkL10H11YRxtcGQ==,type:str]
    pgp:
        - created_at: "2026-04-09T23:40:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA0i7SvTnDueaAQ/+NSsGveJD+DyUtz6EUMa1RPFiH1PTrRn2DxAzjGQG0Oai
            C/JLoZraHHQpkI+JLwLf26D8SCW4rmYtZaJ7g1wrT7v/gcL5jDQnr2mv7ImZwtME
            UsSkr8zreXETT7boXxV5iThzOTZoJ1vTOWCATbqml0i9rxmSFclOL6dujmlsU91O
            ppKdYRBgqIEe7JrAt9mWZ7I0YIYHg9ZRUsEjmqPSbVZd1sTjnQRslCgMkI6LpYB7
            hdiIhGu7uFpfR9VWfJjWhPCald1Q14soqPSV5hHS9p6/cwUnCn3Kragy0XERoSIB
            57tk4U6YpP3b7o34kffNGpudF710OtYuZbc/ffQ7jocnl8k9af/jtTmfSLKrHmA8
            42ELu0H+Cw42dkOBvs2nnpjK9lit6UPmkoOc5lGo6fEjSMaC9Hsv0jqEIkgf7V+u
            wDiT2azdWRQAHPxZhbnbHLM1BuakkqedOUNKpl1IsVFx0PFMH+fIAvgFKMGEYkAk
            ORMv7p4hYUfELI6B80AvA3KCJpiRMw10ocjZQeyt1tSaDlxxwM1aFk2BXbEs3c3A
            Oa7eXSYcHyBc/U0w8j9hIH5CM5Z8MD+saqlfIEilAyTaHEPPUhZYiFVLQibfuhAp
            P+ol+mX6+ERw2QR6OGnodNd9wTdLXZg50G7Aqty+VivuEVQ8p5BjTNDWbavMoFHS
            XgF+Y84JYnNuf86W2X9iAPchEuK7RRBN2pw1xbni38a7doFVIO4iONepW1oioctb
            +9ktJCKq/IzUWpZKFie0JXovWVopHCp5wp4LXDbiLzTZtLlIvrKqruT7iMytXuY=
            =pirU
            -----END PGP MESSAGE-----
          fp: 7EB1A78D86B11352982D3A1F7037153C2DB9CDBD
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
